version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: library-db
    environment:
      POSTGRES_DB: library_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: library-management-system
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: always

volumes:
  pgdata:


